In [11]:
from google.colab import drive
drive.mount('/content/gdrive')
import warnings
warnings.filterwarnings('ignore')
!ls /content/gdrive/MyDrive/'Colab Notebooks'/'HOPE AI'/'WEEK-8.1_Adv_ML'/'capstone'
fileloc='/content/gdrive/MyDrive/Colab Notebooks/HOPE AI/WEEK-8.1_Adv_ML/capstone/'

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).
Algorithm.py		    Model.ipynb		steel_melting_data.csv
Bivariate_Steel.ipynb	    Preprocessed.ipynb	Univariate.py
Deployment.ipynb	    Prep_steel.csv	Univariate_Steel.ipynb
finalized_model_random.sav  __pycache__

In [12]:
import pandas as pd
import numpy as np
import sys
sys.path.append('/content/gdrive/MyDrive/Colab Notebooks/HOPE AI/WEEK-8.1_Adv_ML/capstone')
from Univariate import Univariate

In [13]:
import pandas as pd
from sklearn.model_selection import train_test_split
import time
import numpy as np
from sklearn.preprocessing import StandardScaler
from Algorithm import Algorithm
import pickle
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
import warnings
warnings.filterwarnings('ignore')
sc = StandardScaler()

In [14]:
dataset = pd.read_csv(fileloc + "Prep_steel.csv")

dataset

indep_X = dataset.drop("Steel_Strength", axis=1)

dep_Y = dataset["Steel_Strength"]

indep_X

dep_Y

0      420.25
1      416.32
2      403.06
3      435.25
4      430.28
        ...
495    423.87
496    411.02
497    432.93
498    410.98
499    415.84
Name: Steel_Strength, Length: 500, dtype: float64

In [15]:
X_train, X_test, y_train, y_test = Algorithm.split_scalar(indep_X, dep_Y)

In [16]:
acclin = []
accsvml = []
accdes = []
accrf = []

regressor, r2_lin = Algorithm.Linear(X_train, y_train, X_test, y_test)
acclin.append(r2_lin)

regressor, r2_sl = Algorithm.svm_linear(X_train, y_train, X_test, y_test)
accsvml.append(r2_sl)

regressor, r2_d = Algorithm.Decision(X_train, y_train, X_test, y_test)
accdes.append(r2_d)

regressor, r2_r = Algorithm.random(X_train, y_train, X_test, y_test)
accrf.append(r2_r)

result = Algorithm.regression(
    acclin,
    accsvml,
    accdes,
    accrf
)

In [17]:
result

           Linear      SVMl  Decision    Random
R_Score  0.755906  0.752759  0.109606  0.571991

In [18]:
regressor, r2_random = Algorithm.random(
    X_train,
    y_train,
    X_test,
    y_test
)

sc = StandardScaler()

X_train_scaled = sc.fit_transform(X_train)

X_test_scaled = sc.transform(X_test)

In [24]:
sample = [[
    1580,
    0.35,
    0.28,
    0.82,
    0.02,
    0.03,
    45,
    840,
    72,
    38,
    0.0, # Placeholder for Aluminum_Content
    0.0  # Placeholder for Other_Elements
]]

# Re-initialize and fit StandardScaler 'sc' to ensure it's fitted.
# This assumes X_train is available in the global scope.
sc = StandardScaler()
sc.fit(X_train)

sample_scaled = sc.transform(sample)

prediction = regressor.predict(sample_scaled)

prediction

pickle.dump(
    regressor,
    open(fileloc + "finalized_model_random.sav", "wb")
)

pickle.dump(
    sc,
    open(fileloc + "scaler.sav", "wb")
)