In [10]:
from google.colab import drive
drive.mount('/content/gdrive')
import warnings
warnings.filterwarnings('ignore')
!ls /content/gdrive/MyDrive/'Colab Notebooks'/'HOPE AI'/'WEEK-8.1_Adv_ML'/'capstone'
fileloc='/content/gdrive/MyDrive/Colab Notebooks/HOPE AI/WEEK-8.1_Adv_ML/capstone/'

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).
Algorithm.py		    Model.ipynb		steel_melting_data.csv
Bivariate_Steel.ipynb	    Preprocessed.ipynb	Univariate.py
Deployment.ipynb	    Prep_steel.csv	Univariate_Steel.ipynb
finalized_model_random.sav  __pycache__

In [11]:
import pandas as pd
import numpy as np
import sys
sys.path.append('/content/gdrive/MyDrive/Colab Notebooks/HOPE AI/WEEK-8.1_Adv_ML/capstone')
from Univariate import Univariate
import warnings
warnings.filterwarnings("ignore")

In [13]:
dataset = pd.read_csv(fileloc+"steel_melting_data.csv")

In [14]:
dataset

,Furnace_Temperature,Carbon_Content,Silicon_Content,Manganese_Content,Sulfur_Content,Phosphorus_Content,Oxygen_Level,Power_Consumption,Melting_Time,Cooling_Time,Scrap_Weight,Flux_Added,Steel_Strength
0,1604.9,0.394,0.362,0.718,0.028,0.016,69.5,880.7,65.0,28.3,26.69,127.1,420.25
1,1592.2,0.371,0.109,0.758,0.040,0.030,37.5,858.6,65.3,40.7,30.15,295.5,416.32
2,1608.0,0.307,0.348,0.880,0.036,0.024,46.6,870.3,75.1,27.4,25.71,292.9,403.06
3,1625.5,0.496,0.139,0.813,0.035,0.036,21.3,1007.0,80.8,37.7,15.68,132.7,435.25
4,1590.3,0.382,0.201,1.136,0.024,0.016,38.1,766.6,62.8,27.5,34.59,159.9,430.28
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,1605.8,0.404,0.208,1.061,0.012,0.023,30.2,853.1,93.4,28.7,31.57,177.9,423.87
496,1574.3,0.386,0.126,0.481,0.041,0.023,21.8,884.5,62.1,25.8,39.14,290.3,411.02
497,1591.2,0.426,0.381,0.592,0.027,0.029,32.3,855.6,70.4,25.4,37.90,163.9,432.93
498,1577.5,0.248,0.266,0.514,0.043,0.038,40.4,786.9,70.4,40.5,27.57,273.6,410.98
499,1567.3,0.464,0.192,0.678,0.044,0.012,50.6,817.9,71.2,27.7,34.88,276.3,415.84

In [17]:
dataset.columns

Index(['Furnace_Temperature', 'Carbon_Content', 'Silicon_Content',
       'Manganese_Content', 'Sulfur_Content', 'Phosphorus_Content',
       'Oxygen_Level', 'Power_Consumption', 'Melting_Time', 'Cooling_Time',
       'Scrap_Weight', 'Flux_Added', 'Steel_Strength'],
      dtype='object')

In [18]:
dataset = dataset.drop_duplicates()

numeric_columns = dataset.select_dtypes(include=[np.number]).columns

In [19]:
for column in numeric_columns:
    dataset[column].fillna(dataset[column].median(), inplace=True)

categorical_columns = dataset.select_dtypes(include=['object']).columns

for column in categorical_columns:
    dataset[column].fillna(dataset[column].mode()[0], inplace=True)

dataset.isnull().sum()

Furnace_Temperature    0
Carbon_Content         0
Silicon_Content        0
Manganese_Content      0
Sulfur_Content         0
Phosphorus_Content     0
Oxygen_Level           0
Power_Consumption      0
Melting_Time           0
Cooling_Time           0
Scrap_Weight           0
Flux_Added             0
Steel_Strength         0
dtype: int64

In [20]:
quan, qual = Univariate.quanqual(dataset)

quan_df = dataset[quan]

qual_df = dataset[qual]

dataset.describe()

,Furnace_Temperature,Carbon_Content,Silicon_Content,Manganese_Content,Sulfur_Content,Phosphorus_Content,Oxygen_Level,Power_Consumption,Melting_Time,Cooling_Time,Scrap_Weight,Flux_Added,Steel_Strength
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.00000,500.00000,500.000000,500.00000,500.000000
mean,1595.135800,0.350292,0.249870,0.801538,0.029946,0.025032,49.529800,849.670800,77.32440,34.88720,27.545460,198.71640,416.499020
std,19.625895,0.087263,0.087318,0.231910,0.011520,0.008762,17.071269,41.474607,10.10779,5.78913,7.239448,58.34761,15.602833
min,1530.200000,0.201000,0.101000,0.403000,0.010000,0.010000,20.000000,730.400000,60.00000,25.00000,15.150000,100.80000,362.660000
25%,1581.000000,0.270750,0.171000,0.596000,0.021000,0.018000,33.975000,820.675000,68.40000,29.77500,21.440000,146.85000,406.527500
50%,1595.300000,0.351500,0.255000,0.805000,0.030000,0.025000,49.400000,851.750000,77.20000,34.60000,27.585000,198.25000,416.750000
75%,1607.750000,0.427250,0.320250,1.009000,0.040000,0.032000,64.925000,878.825000,86.22500,40.00000,33.502500,251.82500,427.110000
max,1672.100000,0.499000,0.400000,1.199000,0.050000,0.040000,80.000000,1007.000000,94.90000,44.80000,39.980000,299.90000,458.840000

In [21]:
preprocessed = pd.concat([quan_df, qual_df], axis=1)

preprocessed

preprocessed.to_csv(fileloc + "Prep_steel.csv", index=False)