In [14]:
from google.colab import drive
drive.mount('/content/gdrive')
import warnings
warnings.filterwarnings('ignore')
!ls /content/gdrive/MyDrive/'Colab Notebooks'/'HOPE AI'/'WEEK-10-Rec_sys'
fileloc="/content/gdrive/MyDrive/Colab Notebooks/HOPE AI/WEEK-10-Rec_sys"
fileloccsv="/content/gdrive/MyDrive/Colab Notebooks/HOPE AI/WEEK-10-Rec_sys/content_vector.csv"

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).
Advml_Recom-debug-set-1.ipynb	    content_vector.csv
Advml_Recom-debug-set-2.ipynb	    ml-100k
Combined_ML_Scenario_Questions.pdf  RecommendationSystem.ipynb

In [15]:
import pandas as pd
import numpy as np

In [16]:
i_cols = ['movie id', 'movie title' ,'release date','video release date', 'IMDb URL', 'unknown', 'Action', 'Adventure',
    'Animation', 'Children\'s', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy',
    'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']
items = pd.read_csv(fileloc+'/ml-100k/u.item', sep='|', names=i_cols,encoding='latin-1')

In [17]:
movie_content=items[['movie id','movie title','Action', 'Adventure',
    'Animation', 'Children\'s', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy',
    'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']]
movie_content

,movie id,movie title,Action,Adventure,Animation,Children's,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye (1995),1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
2,3,Four Rooms (1995),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
3,4,Get Shorty (1995),1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0
4,5,Copycat (1995),0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1677,1678,Mat' i syn (1997),0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1678,1679,B. Monkey (1998),0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0
1679,1680,Sliding Doors (1998),0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0
1680,1681,You So Crazy (1994),0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1681,1682,Scream of Stone (Schrei aus Stein) (1991),0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0

In [18]:
content_vector = pd.read_csv(fileloccsv)
content_vector

,0,1,2,3,4,5,6,7,8,9,...,933,934,935,936,937,938,939,940,941,942
0,0.470588,0.338710,0.222222,0.166667,0.714286,0.454976,0.339950,0.220339,0.272727,0.336957,...,0.482759,0.282051,0.373239,0.375,0.518519,0.346939,0.457944,0.545455,0.493671,0.398810
1,0.621324,0.403226,0.722222,0.958333,0.617143,0.336493,0.570720,1.254237,0.545455,0.396739,...,0.482759,0.871795,0.478873,0.325,0.777778,0.816327,0.514019,1.090909,0.620253,0.797619
2,0.191176,0.193548,0.388889,0.458333,0.108571,0.113744,0.191067,0.305085,0.227273,0.184783,...,0.120690,0.282051,0.197183,0.100,0.296296,0.244898,0.186916,0.318182,0.253165,0.208333
3,1.003676,0.983871,0.888889,0.750000,0.942857,0.924171,0.816377,1.118644,0.954545,0.831522,...,0.971264,1.076923,1.007042,1.075,0.990741,1.040816,1.056075,1.000000,0.898734,1.053571
4,0.676471,0.903226,0.981481,0.875000,0.314286,0.672986,0.632754,0.745763,0.727273,0.711957,...,0.563218,0.820513,0.767606,0.775,0.648148,0.673469,0.700935,0.590909,0.645570,0.654762
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1677,0.393382,0.564516,0.407407,0.250000,0.154286,0.492891,0.362283,0.288136,0.500000,0.440217,...,0.390805,0.461538,0.478873,0.625,0.296296,0.367347,0.448598,0.227273,0.392405,0.339286
1678,0.352941,0.451613,0.481481,0.583333,0.217143,0.308057,0.330025,0.423729,0.590909,0.380435,...,0.327586,0.589744,0.415493,0.325,0.490741,0.448980,0.411215,0.363636,0.468354,0.404762
1679,0.555147,0.822581,0.500000,0.375000,0.262857,0.687204,0.501241,0.406780,0.863636,0.635870,...,0.597701,0.769231,0.697183,0.850,0.490741,0.571429,0.672897,0.272727,0.607595,0.535714
1680,0.334559,0.258065,0.222222,0.166667,0.468571,0.312796,0.218362,0.169492,0.272727,0.255435,...,0.362069,0.230769,0.338028,0.300,0.370370,0.306122,0.392523,0.318182,0.278481,0.333333
1681,0.393382,0.564516,0.407407,0.250000,0.154286,0.492891,0.362283,0.288136,0.500000,0.440217,...,0.390805,0.461538,0.478873,0.625,0.296296,0.367347,0.448598,0.227273,0.392405,0.339286

In [21]:
def top5movies(content_vectors,movie_content):
    val_list = []
    for i in content_vectors:
        val = content_vectors[i].max()
        val_list.append(val)

    val_df=pd.DataFrame(val_list)
    val_df.columns = ['max_id']
    result = (val_df.sort_values(by='max_id', ascending=False)).head(5)
    movie_titles = movie_content[movie_content['movie id'].isin (result.index)][['movie title','Action', 'Adventure',
    'Animation', 'Children\'s', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy','Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']]

    genre_cols = movie_titles.columns.drop('movie title')
    movie_titles['Active_Genres'] = movie_titles[genre_cols].apply(lambda row: row.index[row == 1].tolist(), axis=1)
    result = movie_titles[['movie title', 'Active_Genres']]
    return result

In [23]:
movie_titles = top5movies(content_vector,movie_content)
movie_titles

                      movie title       Active_Genres
125    Spitfire Grill, The (1996)             [Drama]
335            Playing God (1997)   [Crime, Thriller]
469              Tombstone (1993)           [Western]
582      Romeo Is Bleeding (1993)   [Crime, Thriller]
601  American in Paris, An (1951)  [Musical, Romance]