In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
!ls /content/gdrive/MyDrive/'Colab Notebooks'/'HOPE AI'/'WEEK-8.1_Adv_ML'
fileloc="/content/gdrive/MyDrive/Colab Notebooks/HOPE AI/WEEK-8.1_Adv_ML/prep.csv"
dataset = pd.read_csv(fileloc)
dataset.isnull().sum()

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).
prep.csv  SelectKalgorithm.ipynb

age               0
bp                0
sg                0
al                0
su                0
rbc               0
pc                0
pcc               0
ba                0
bgr               0
bu                0
sc                0
sod               0
pot               0
hrmo              0
pcv               0
wc                0
rc                0
htn               0
dm                0
cad               0
appet             0
pe                0
ane               0
classification    0
dtype: int64

Libs

In [ ]:
from sklearn.model_selection import train_test_split
import time
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
import pickle
import matplotlib.pyplot as plt

separate Functions

In [ ]:
def Decision(X_train,y_train,X_test):

        from sklearn.tree import DecisionTreeRegressor
        regressor = DecisionTreeRegressor(random_state = 0)
        regressor.fit(X_train, y_train)
        r2=r2_prediction(regressor,X_test,y_test)
        return  r2

def split_scalar(indep_X,dep_Y):
        X_train, X_test, y_train, y_test = train_test_split(indep_X, dep_Y, test_size = 0.25, random_state = 0)
        sc = StandardScaler()
        X_train = sc.fit_transform(X_train)
        X_test = sc.transform(X_test)
        return X_train, X_test, y_train, y_test







def svm_NL(X_train,y_train,X_test):

        from sklearn.svm import SVR
        regressor = SVR(kernel = 'rbf')
        regressor.fit(X_train, y_train)
        r2=r2_prediction(regressor,X_test,y_test)
        return  r2

def Linear(X_train,y_train,X_test):
        from sklearn.linear_model import LinearRegression
        regressor = LinearRegression()
        regressor.fit(X_train, y_train)
        r2=r2_prediction(regressor,X_test,y_test)
        return  r2



def selectkbest(indep_X,dep_Y,n):
        test = SelectKBest(score_func=chi2, k=n)
        fit1= test.fit(indep_X,dep_Y)
        selectk_features = fit1.transform(indep_X)
        return selectk_features

def random(X_train,y_train,X_test):
        from sklearn.ensemble import RandomForestRegressor
        regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
        regressor.fit(X_train, y_train)
        r2=r2_prediction(regressor,X_test,y_test)
        return  r2

def r2_prediction(regressor,X_test,y_test):
     y_pred = regressor.predict(X_test)
     from sklearn.metrics import r2_score
     r2=r2_score(y_test,y_pred)
     return r2


def svm_linear(X_train,y_train,X_test):

        from sklearn.svm import SVR
        regressor = SVR(kernel = 'linear')
        regressor.fit(X_train, y_train)
        r2=r2_prediction(regressor,X_test,y_test)
        return  r2

def selectk_regression(acclin,accsvml,accsvmnl,accdes,accrf):

    dataframe=pd.DataFrame(index=['ChiSquare'],columns=['Linear','SVMl','SVMnl','Decision','Random'
                                                                                     ])

    for number,idex in enumerate(dataframe.index):

        dataframe['Linear'][idex]=acclin[number]
        dataframe['SVMl'][idex]=accsvml[number]
        dataframe['SVMnl'][idex]=accsvmnl[number]
        dataframe['Decision'][idex]=accdes[number]
        dataframe['Random'][idex]=accrf[number]
    return dataframe

In [ ]:
dataset1=pd.read_csv(fileloc,index_col=None)

df2=dataset1

df2 = pd.get_dummies(df2, drop_first=True)

indep_X=df2.drop('classification_yes', axis =1)
dep_Y=df2['classification_yes']

In [ ]:
kbest=selectkbest(indep_X,dep_Y,7)

print(kbest)

acclin=[]
accsvml=[]
accsvmnl=[]
accdes=[]
accrf=[]

[[3.00000000e+00 1.48112676e+02 5.74821053e+01 ... 1.25181556e+01
  3.88689024e+01 8.40819113e+03]
 [2.00000000e+00 1.48112676e+02 2.20000000e+01 ... 1.07000000e+01
  3.40000000e+01 1.23000000e+04]
 [1.00000000e+00 9.90000000e+01 2.30000000e+01 ... 1.20000000e+01
  3.40000000e+01 8.40819113e+03]
 ...
 [3.00000000e+00 1.10000000e+02 1.15000000e+02 ... 9.10000000e+00
  2.60000000e+01 9.20000000e+03]
 [0.00000000e+00 2.07000000e+02 8.00000000e+01 ... 8.50000000e+00
  3.88689024e+01 8.40819113e+03]
 [0.00000000e+00 1.00000000e+02 4.90000000e+01 ... 1.63000000e+01
  5.30000000e+01 8.50000000e+03]]

In [ ]:
X_train, X_test, y_train, y_test=split_scalar(kbest,dep_Y)
#call linear func
r2_lin=Linear(X_train,y_train,X_test)
acclin.append(r2_lin)
#call support vector func
r2_sl=svm_linear(X_train,y_train,X_test)
accsvml.append(r2_sl)
#call svmnl func
r2_NL=svm_NL(X_train,y_train,X_test)
accsvmnl.append(r2_NL)
#call decision trree func
r2_d=Decision(X_train,y_train,X_test)
accdes.append(r2_d)
#call random forest func
r2_r=random(X_train,y_train,X_test)
accrf.append(r2_r)


result=selectk_regression(acclin,accsvml,accsvmnl,accdes,accrf)

In [ ]:
result

             Linear      SVMl     SVMnl  Decision    Random
ChiSquare  0.657035  0.641906  0.893007  0.826389  0.916233